version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: inventario_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: inventariodb
    ports:
      - "5432:5432"
    volumes:
      # Persistencia de datos
      - pgdata:/var/lib/postgresql/data
      # Ejecuta los scripts SQL al inicializar por primera vez
      - ./init_db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # Servicio del Backend en Node.js
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: inventario_api
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      - DB_NAME=inventariodb
      - DB_PORT=5432
      - JWT_SECRET=super_secret_key_123
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      # Sincroniza los cambios en desarrollo sin tener que reconstruir la imagen
      - ./src:/app/src
    restart: unless-stopped

volumes:
  pgdata:
    name: inventario_pgdata